version: '3'

tasks:
  binclude:
    desc: Generate embed files
    dir: internal/app
    cmds:
      - binclude

  install:
    desc: Build and install
    cmds:
      - go build -i -o go8gen main.go
      - mv go8gen ~/go/bin/go8gen